### ISSUE TITLE
some characteristic properties not working 

### ISSUE THREAD

**Issue by bllsvr** [jenow/flutter-ble#5]
Hi , i am using your example app or any app that include flutter_blue package . I want to read , write and notify to some characteristics.

I'm having trouble writing to a characteristic.  When i use another package or another app , i can write to this characteristic.
But when i use flutter blue , It says me "there is no ability to write to this characteristic" something like this.  I mean "characteristic.properties.write=false " .    

What can i do ? 

Thanks...

**Comment by noemyroberta** [comment]
hi, @bllsvr!
i'm trying to implement the bluetooth connection as you. did you get some progress with this code for your project?

i'll be grateful if you let me know.

**Comment by jenow** [comment]
Hi @bllsvr, @noemyroberta 

I don't really know but I just migrated the project with flutter_blue_plus as flutter_blue is not maintained anymore so maybe you could give it another try now.

**Comment by rahulraikwar00** [comment]
Hi I'm trying to clone this app "Cardcast" business card sharing app using ble advertise
Can you please guide me how it's working and how can i achieve the same feature?
